- azit-back/src/main/java/com/codestates/azitserver/HealthCheckController.java
> [# 이슈번호]통신테스트 변수 변경

- .gitignore
- azit-back/src/main/java/com/codestates/azitserver/HealthCheckController.java
변수를 변경했습니다.
변수 hello, everyone으로 추가
-
-
> [#이슈번호] 통신테스트 변수 변경2

- azit-back/src/main/java/com/codestates/azitserver/HealthCheckController.java
> [scope] title

- azit-back/src/main/java/com/codestates/azitserver/domain/member/entity/Member.java
- azit-back/src/main/java/com/codestates/azitserver/domain/review/entity/review.java
- azit-back/src/main/java/com/codestates/azitserver/global/Audit/Auditable.java
회원, 리뷰 엔티티 구현
- 회원 엔티티
- 리뷰 엔티티
- 엔티티의 생성, 수정일자를 위한 Auditable 클래스
- FK로 연관관계 매핑 예정사항을 표시해두었습니다
> [member, review] 회원, 리뷰 엔티티 구현

- azit-front/src/components/LoginComponent/Button.js
- azit-front/src/pages/FindPassword.js
- azit-front/src/pages/SignupAdditional.js
- Login page 마크업 완료
- Signup page 마크업 완료
- FindPassword page 마크업 완료
> chore: Login / Signup page Mark Up

- azit-front/src/App.js
- azit-front/src/components/AzitCreate/AzitcreateForm.js
- azit-front/src/components/AzitEdit/AzitEditForm.js
- azit-front/src/components/Button.js
- azit-front/src/pages/AzitEdit.js
1. AzitEditPage 마크업 작업 완료
2. component 안에 Button.js 컴포넌트 수정
3. AzitCreatePage 마크업 작업 수정 완료
> add AzitEditPage & edit button component, AzitCreatePage

- azit-front/src/App.js
- azit-front/src/pages/AzitJoin.js
> AzitJoin markup

- azit-front/src/App.js
- azit-front/src/GlobalStyle.js
- azit-front/src/components/AzitCreate/AzitcreateForm.js
- azit-front/src/components/AzitEdit/AzitEditForm.js
- azit-front/src/pages/AzitEdit.js
- azit-front/src/pages/AzitReport.js
- AzitReportPage 마크업 작업 완료 
- select css 수정
- GlobalStyle 수정
> [Chore] AzitReportPage 마크업 작업 완료 & select css 수정 & GlobalStyle 수정

- azit-front/src/App.js
- azit-front/src/pages/Loading.js
- azit-front/src/pages/Login.js
- azit-front/src/pages/Signup.js
- azit-front/src/pages/SignupAdditional.js
- Login / Signup page 라우팅 구조 구현
> [chore] Login / Signup page 라우팅 구조 구현

- azit-front/src/App.js
- azit-front/src/components/LoginComponent/Button.js
- azit-front/src/pages/Login.js
- azit-front/src/pages/UserProfileEdit.js
- UserProfileEdit page Markup
- LoginComponents 내 Button styled component 코드 수정
- Login 페이지에 비회원으로 시작 버튼 추가
> [chore] UserProfileEdit page Markup

- azit-front/src/App.js
- azit-front/src/pages/UserResetPassword.js
> [chore] UserResetPassword page Markup

- azit-front/src/App.js
> App.js 오타 수정

- azit-front/src/App.js
- azit-front/src/components/Header.js
- azit-front/src/pages/AzitPreview.js
- Header 수정
- AzitPreviewPage MarkUp
> Header 수정 & AzitPreviewPage MarkUp

- azit-front/src/pages/AzitDetail.js
- azit-front/src/pages/AzitPreview.js
AzitDetail.js,AzitPreview.js 마진 수정
> AzitDetail.js,AzitPreview.js 마진 수정

- azit-front/src/pages/Azitcreate.js
> Azitcreatepage Img Modal 추가

- azit-front/src/App.js
> App.js 반복 사용된 라우트 제거

- azit-front/src/components/AzitCreate/AzitcreateForm.js
> location Modal 추가

- azit-front/src/components/MyPage/ActivityHistory.js
- azit-front/src/components/MyPage/Category.js
- azit-front/src/components/MyPage/Profile.js
- azit-front/src/components/MyPage/Reviews.js
- azit-front/src/components/UserPageHeader.js
> Chore/userPage 수정

- azit-front/src/pages/SignupAdditional.js
관심사 카테고리 구현
- 추가적인 css 스타일링 필요
- 카테고리 선택시 check된 값 불러오기
> 관심사 카테고리 구현

- azit-front/src/pages/SignupAdditional.js
> 관심사 카테고리 색상 추가

- azit-front/src/components/common/Modal.js
- 비회원 유저가 메인페이지 이외 다른 페이지에 접근 시도할 시 필요한 LoginRequestModal 구현 완료
> [chore] LoginRequestModal 구현

- azit-front/package-lock.json
- azit-front/package.json
- azit-front/src/components/AzitCreate/AzitCreateForm.js
- azit-front/src/pages/AzitCreate.js
- azit-front/src/pages/AzitDetail.js
azitCreate 기능 구현(완성 전 코드 리뷰를 위함)
> feat: azitCreate 기능 구현

- azit-front/src/components/AzitCreate/AzitCreateForm.js
> feat: 소분류 카테고리 구현

- azit-back/src/docs/asciidoc/index.adoc
- azit-back/src/main/java/com/codestates/azitserver/domain/member/controller/MemberController.java
- azit-back/src/main/java/com/codestates/azitserver/domain/member/dto/MemberDto.java
- azit-back/src/main/java/com/codestates/azitserver/domain/member/entity/Member.java
- azit-back/src/main/java/com/codestates/azitserver/domain/member/mapper/MemberMapper.java
- azit-back/src/main/java/com/codestates/azitserver/domain/member/service/MemberService.java
- azit-back/src/main/java/com/codestates/azitserver/global/config/SecurityConfig.java
- azit-back/src/test/java/com/codestates/azitserver/domain/member/controller/MemberControllerTest.java
- azit-back/src/test/java/com/codestates/azitserver/domain/member/controller/MemberFieldDescriptor.java
- azit-back/src/test/java/com/codestates/azitserver/domain/stub/MemberStubData.java
1. 회원 프로필사진 post 구현
2. 1과 관련된 api 문서 생성, adoc 수정
3. 회원 도메인 권한 설정
1. 회원 도메인 controller, dto, service 수정
2. 테스트 코드 수정
3. securityConfig 수정
1d
> [member] 회원 프로필사진 구현 및 adoc, 회원 도메인 권한 설정

- azit-front/src/components/AzitCreate/AzitCreateForm.js
- azit-front/src/pages/AzitCreate.js
> feat: 주소 검색 기능 구현

- azit-front/package-lock.json
- azit-front/src/components/Logout/LogoutRequestModal.js
- azit-front/src/pages/Login.js
- azit-front/src/pages/Signup.js
- azit-front/src/pages/UserPageSetting.js
- 로그인 시 이메일과 비밀번호 입력하지 않을 경우, input 밑 에러메시지 표시 구현
- 유저 로그아웃 클릭 시 표시되는 LogoutRequestModal  구현
- 로그아웃 기능 구현
> [feat] 로그인 에러핸들링 및 로그아웃 기능 구현

- azit-front/src/components/AzitCreate/AzitCreateForm.js
- azit-front/src/pages/AzitCreate.js
- azit-front/src/pages/AzitDetail.js
- azit-front/src/pages/AzitPreview.js
- azit-front/src/util/azitPreviewDateConvert.js
useNavigate와 uselocation을 이용하여 AzitCreate에서 AzitPreview로 데이터를 전달받아
현재 상황에서는 호스트의 이미지 데이터를 받아올 수 없기 때문에 호스트 프로필 이미지를 제외한
AzitCreate에서 입력받은 데이터를 AzitPreview에 반영하였습니다.
마지막으로, 데이터 변환을 위해 필요한 함수를 추가하였습니다.
> [Feat] AzitPreview 구현 및 필요한 함수 추가

- azit-front/src/pages/AzitCreate.js
> [fix]아지트 생성 페이지 내 이미지 첨부 방식 수정

- azit-back/src/main/java/com/codestates/azitserver/domain/auth/filter/JwtAuthenticationFilter.java
- azit-back/src/main/java/com/codestates/azitserver/domain/auth/handler/OAuthSuccessHandler.java
프로필 사진이 없을 때 nullpointerexception 발생하는 것 해결
setProfileUrl 부분에서 에러가 발생하는 것으로 확인되어, 예외처리로 프로필 null이어도 로그인 되도록 수정
> [hotfix/auth] 로그인 이미지 null 에러

- azit-front/src/components/AzitCreate/AzitCreateForm.js
- azit-front/src/pages/AzitDetail.js
- azit-front/src/pages/AzitPreview.js
- 아지트 미리보기 페이지 및 아지트 상세 페이지 마크업 수정
- 아지트 생성 페이지 코드 수정
> [fix]아지트 미리보기 페이지 및 아지트 상세 페이지 마크업 수정/ 아지트 생성 페이지 코드 수정

- azit-front/src/components/AzitCreate/AzitCreateForm.js
- azit-front/src/pages/AzitDetail.js
- azit-front/src/pages/AzitPreview.js
minYear 선택에 따른 maxYear 선택지 제한 걸기 추가
> [fix] minYear 선택에 따른 maxYear 선택지 제한 걸기 추가

- azit-front/src/components/AzitEdit/AzitEditForm.js
> fix: 아지트 수정 페이지 마크업 수정

- azit-front/src/components/AzitCreate/AzitCreateForm.js
- azit-front/src/components/AzitEdit/AzitEditForm.js
- azit-front/src/pages/AzitDetail.js
- azit-front/src/pages/AzitPreview.js
AzitDetail 과 AzitPreview 마크업 수정
> fix: AzitDetail 과 AzitPreview 마크업 수정

- azit-front/src/App.js
- azit-front/src/pages/Login.js
- azit-front/src/pages/UserPageSetting.js
- azit-front/src/pages/UserVerifyPassword.js
- 비밀번호 인증을 위한 UserVerifyPassword 페이지 추가 및 경로 설정
- 비밀번호 인증 기능 구현
- 로그인 시 응답값으로 오는 memberId를 로컬 스토리지에 저장
> [feat] 비밀번호 인증 기능 및 로그인 시 memberId 로컬 저장 기능 구현

- azit-back/src/main/java/com/codestates/azitserver/domain/fileInfo/service/StorageService.java
- azit-back/src/main/java/com/codestates/azitserver/domain/fileInfo/service/StorageServiceAwsS3.java
- azit-back/src/main/java/com/codestates/azitserver/domain/fileInfo/service/StorageServiceLocal.java
- azit-back/src/main/java/com/codestates/azitserver/global/exception/StorageException.java
- azit-back/src/main/java/com/codestates/azitserver/global/exception/advice/GlobalExceptionAdvice.java
- azit-back/src/main/java/com/codestates/azitserver/global/exception/dto/ExceptionCode.java
클라이언트쪽에서 제보해주신 에러 수정하여 업로드 합니다.
- BusinessLogicException 응답코드 400번대로 출력되게 수정
- 아지트 배너 이미지 저장 경로 문제 수정
> [hotfix] 예외처리, 아지트 배너 이미지 경로 설정 문제

- azit-front/src/App.js
- azit-front/src/components/AzitDetail/AzitDetailHeader.js
- azit-front/src/components/AzitEdit/AzitEditForm.js
- azit-front/src/pages/AzitDetail.js
- azit-front/src/pages/AzitSetting.js
아지트 상세 페이지에서 설정 페이지로 넘어가는 링크 수정
설정페이지에서 아지트 수정 페이지로 넘어가는 링크 추가
> fix: 링크 연결 수정

- azit-front/src/dummyData/SignupYear.js
- azit-front/src/pages/Signup.js
- azit-front/src/pages/SignupAdditional.js
- azit-front/src/pages/UserResetPassword.js
- azit-front/src/pages/UserVerifyPassword.js
- 비밀번호 변경 기능 구현 완료
- 통신을 제외한 회원 가입 기능 구현
> [feat] 비밀번호 변경 기능 구현 완료 및 회원 가입 기능 부분 구현

- azit-front/src/App.js
- azit-front/src/components/MyPage/Category.js
- azit-front/src/components/MyPage/Profile.js
- azit-front/src/components/MyPage/UserPageHeader.js
- azit-front/src/pages/UserPage.js
- azit-front/src/pages/UserProfileEdit.js
유저페이지에서 프로필이미지, 닉네임, 자기소개, 온도계기능(평판점수),카테고리 데이터 받아와서 렌더링하는 기능 구현했습니다.
> [Feat] 유저페이지 기능 구현 

- azit-back/scripts/deploy.sh
- azit-back/scripts/deploy_main.sh
> [deploy] prod server 실행하는 쉘스크립트 작성

- azit-front/src/components/Logout/LogoutRequestModal.js
- 회원 가입 기능 통신 테스트 완료
- LogoutRequestModal UI 수정
> [feat] 회원 가입 기능 구현 완료 및 LogoutRequestModal UI 수정

- azit-back/src/main/java/com/codestates/azitserver/domain/club/service/ClubService.java
- azit-back/src/main/java/com/codestates/azitserver/domain/member/service/MemberService.java
- azit-back/src/main/java/com/codestates/azitserver/global/config/SecurityConfig.java
cors 추가
FE에서 만들어주신 페이지 주소 추가했습니다.
> [auth] 배포 테스트에 따른 cors 추가

- azit-front/src/pages/Signup.js
- azit-front/src/pages/UserResetPassword.js
- azit-front/src/pages/UserVerifyPassword.js
- 비밀번호 유효성 검사에서 (~) 를 허용하도록 수정하였습니다.
> [fix] 비밀번호 유효성 검사 수정

- azit-back/src/main/java/com/codestates/azitserver/domain/auth/dto/AuthDto.java
- azit-back/src/main/java/com/codestates/azitserver/domain/auth/filter/JwtAuthenticationFilter.java
- azit-back/src/main/java/com/codestates/azitserver/domain/auth/handler/OAuthSuccessHandler.java
- azit-back/src/test/java/com/codestates/azitserver/domain/auth/authLoginTest.java
FE 요청에 따라 로그인 응답값에 프로필 이미지명이 나오도록 수정했습니다.
- AuthDto 수정
- JwtAuthenticationFilter 수정
- OAuthSuccessHandler 수정
비밀번호 변경 입력 dto에 비밀번호 유효성 검증 추가
> [hotfix/auth] 로그인 응답값 수정

- azit-front/src/components/MyPage/UserPageHeader.js
- azit-front/src/pages/UserPage.js
- azit-front/src/pages/UserProfileEdit.js
input창에 accept 수정, 닉네임 중복될시 alert창 열리게  수정.
> [Feat] 유저페이지 기능 구현

- azit-front/src/components/AzitCreate/AzitCreateForm.js
- azit-front/src/components/AzitEdit/AzitEditForm.js
- azit-front/src/pages/AzitCreate.js
- azit-front/src/pages/AzitDetail.js
- azit-front/src/pages/AzitPreview.js
- azit-front/src/util/azitPreviewDateConvert.js
날짜 제한, 멤버 제한,아지트 수정page 뒤로가기 네비게이션 수정
> fix: 날짜 제한, 멤버 제한,아지트 수정page 뒤로가기 네비게이션 수정

- azit-front/src/components/AzitSetting/AzitDeleteModal.js
- azit-front/src/pages/AzitPreview.js
- azit-front/src/pages/AzitSetting.js
> [feat] 아지트 미리보기 페이지 호스트 이미지 반영

- azit-front/src/components/AzitEdit/AzitEditForm.js
아지트 수정 멤버 신청 상태에 따라 수정제한 항목 추가
> fix: 아지트 수정 멤버 신청 상태에 따라 수정제한 항목 추가

- azit-front/src/pages/AzitSetting.js
아지트 삭제 기능 구현
상태코드 202뜨고 res도 잘 오는데 검색 시 아직 해당 아지트가 존재함.
그 부분 이슈 공유해야 할 예정
> [feat] 아지트 삭제 기능 구현

- azit-front/src/App.js
- azit-front/src/components/AzitCreate/AzitCreateForm.js
- azit-front/src/pages/AzitDetail.js
- azit-front/src/pages/AzitJoin.js
:아지트 상세 페이지에서 아지트 참가 신청 페이지로 연결
> [feat]아지트 상세 페이지에서 아지트 참가 신청 페이지로 연결

- azit-back/src/main/java/com/codestates/azitserver/domain/club/dto/ClubDto.java
- azit-back/src/main/java/com/codestates/azitserver/domain/review/controller/ReviewController.java
- azit-back/src/main/java/com/codestates/azitserver/domain/review/dto/ReviewDto.java
- azit-back/src/main/java/com/codestates/azitserver/domain/review/entity/Review.java
- azit-back/src/main/java/com/codestates/azitserver/domain/review/mapper/ReviewMapper.java
- azit-back/src/main/java/com/codestates/azitserver/domain/review/repository/ReviewRepository.java
- azit-back/src/main/java/com/codestates/azitserver/domain/review/service/ReviewService.java
- azit-back/src/main/java/com/codestates/azitserver/global/config/SecurityConfig.java
- azit-back/src/main/java/com/codestates/azitserver/global/exception/dto/ExceptionCode.java
issue #211  
사용자가 참여한 아지트 모임 참석자에 대한 리뷰를 작성하는 도메인 구현했습니다.
- 아지트 참여자에 대한 리뷰 작성 기능
- 회원은 본인에 대해 쓴 리뷰를 숨김처리/해제할 수 있습니다.
- 모든 사용자는 특정 사용자에대한 리뷰를 조회할 수 있습니다.
- 리뷰 작성은 아지트 모임 참여자에 대해서만 가능합니다. 모임에 없는 사용자에 대한 리뷰는 금지합니다.(작성자도 동일)
- 리뷰를 작성하면 리뷰 대상자에 대한 평판점수가 1 증가합니다.
- api 테스트는 저녁 먹고 작성 예정(5시에 일정이 있어서ㅠㅠ)
> [Review] 리뷰 CRUD 기능 구현

- azit-front/src/pages/AzitJoin.js
> [feat] 아지트 참가신청 기능 구현

- azit-front/src/App.js
- azit-front/src/components/AzitMember/Member.js
- azit-front/src/components/AzitMember/MemberList.js
- azit-front/src/components/AzitMember/WaitingMember.js
- azit-front/src/pages/AzitMember.js
- azit-front/src/pages/AzitSetting.js
아지트 신청/참가 멤버 조회 기능 구현했습니다.
아지트 신청/참가 멤버 데이터에 멤버의 자기소개(userIntroduce)가 필요하여 그 부분은 추후 요청 드릴 예정
> [feat] 아지트 신청/참가 멤버 조회 기능 구현

- azit-front/src/pages/FindPassword.js
- 비밀번호 찾기를 위한 이메일 인증 기능을 구현하였습니다.
- 인증 후 인증번호 입력 기능을 구현하였습니다.
- common Button 컴포넌트에 onClick 이벤트가 전달되지 않고 있어 수정 논의가 필요합니다.
> [feat] 비밀번호 찾기 기능 구현

- azit-front/src/App.js
- azit-front/src/pages/FindPassword.js
- azit-front/src/pages/UserPageSetting.js
- azit-front/src/pages/UserWithdrawl.js
- 회원 탈퇴를 누르면 이동하게 될 UserWithdrawl 페이지를 구현하였습니다.
- 유저 설정 페이지에서 회원탈퇴를 누르면 UserWithdrawl 페이지로 이동하도록 경로를 설정하였습니다.
- 회원 탈퇴 기능을 구현하였습니다.
- common Button 컴포넌트에 onClick 이벤트가 전달되지 않고 있어 수정 논의가 필요합니다. (비밀번호 찾기 기능 pr 이슈와 동일) -> 상위 컴포넌트 form으로 변경 후 onSubmit으로 대체하여 함수 전달하는 것으로 해결 완료
> [feat] 회원 탈퇴 기능 구현

- azit-front/src/pages/AzitDetail.js
아지트 유저별 상태에 따른 아지트 상세 페이지 버튼 변화 추가
아래 해당하는 오류는 현재 원인이 제대로 파악되지 않아  추후 원인 파악 및 해결할 예정
- 가입하기 버튼의 경우 나타나지 않을 때가 있으며 새로고침해야 나오는 경우 발생
- 종종 버튼이 동시에 두개가 나오는 경우 발생
> feat: 아지트 유저별 상태에 따른 아지트 상세 페이지 버튼 변화

- azit-front/src/pages/AzitDetail.js
아지트 상세 페이지 버튼 오류 수정
- 추후 계속 제대로 작동되는지 확인필요
> fix: 아지트 상세 페이지 버튼 오류 수정

- azit-front/package-lock.json
- azit-front/package.json
- azit-front/src/components/AzitCreate/AzitCreateForm.js
- azit-front/src/components/AzitCreate/ImageModal.js
- azit-front/src/pages/AzitCreate.js
- azit-front/src/pages/AzitPreview.js
아지트 생성 페이지에서 사용자가 배너 이미지를 첨부시 이미지를 크롭할 수 있는 기능 구현
> feat: 배너 이미지 크롭 기능 구현

- azit-front/src/components/AzitMember/MemberList.js
> fix: 강퇴 기능 오류 수정

- azit-front/src/pages/UserPageSetting.js
> feat: 로그아웃 통신 기능 구현 완료

- azit-back/src/main/java/com/codestates/azitserver/global/config/SecurityConfig.java
- azit-back/src/main/resources/application.yml
임시로 변경했던 토큰 시간을 정상으로 돌려놨습니다.
토큰 시간 변경
securityConfig에 변경된 api 적용
> [auth/hotfix] 토큰 시간 정상화

- azit-back/src/main/java/com/codestates/azitserver/domain/follow/controller/FollowController.java
- azit-back/src/main/java/com/codestates/azitserver/domain/follow/dto/FollowDto.java
- azit-back/src/main/java/com/codestates/azitserver/domain/follow/entity/Follow.java
- azit-back/src/main/java/com/codestates/azitserver/domain/follow/mapper/FollowMapper.java
- azit-back/src/main/java/com/codestates/azitserver/domain/follow/repository/FollowRepository.java
- azit-back/src/main/java/com/codestates/azitserver/domain/follow/service/FollowService.java
- azit-back/src/main/java/com/codestates/azitserver/domain/member/controller/MemberController.java
- azit-back/src/main/java/com/codestates/azitserver/domain/member/entity/Member.java
- azit-back/src/main/java/com/codestates/azitserver/global/config/SecurityConfig.java
- azit-back/src/main/java/com/codestates/azitserver/global/exception/dto/ExceptionCode.java
팔로우 기능 일부 구현한 내용 업로드합니다 
- 팔로우 언팔로우 기능
- 팔로워 조회 기능
> [Member/Follow] 팔로우 기능 구현(일부)

- azit-front/src/components/AzitMember/MemberList.js
> fix: 아지트 강퇴 기능 axios로 수정

- azit-front/src/components/AzitMember/MemberList.js
> fix: 아지트 신청 멤버 수락,거절, 강퇴시 바로 반영

- azit-back/src/main/java/com/codestates/azitserver/domain/auth/controller/AuthController.java
- azit-back/src/test/java/com/codestates/azitserver/domain/auth/authControllerTest.java
토큰재발급 cors 해결 후 Not Found에 대한 해결 시도
이메일 뒤에 / 붙여서 이메일이 잘리지 않도록 수정
> [auth] api 주소 수정

- azit-front/src/components/AzitMember/Member.js
- azit-front/src/components/AzitMember/WaitingMember.js
> fix: 아지트 멤버 렌더링 시 오류 수정

- azit-back/src/main/java/com/codestates/azitserver/domain/auth/handler/OAuthSuccessHandler.java
oauth 코드 에러 확인을 위해서 임시 변경
확인후 복구하겠습니다..
> [auth]에러 확인을 위해 oauth코드 임시 변경

- azit-back/src/docs/asciidoc/index.adoc
- azit-back/src/main/java/com/codestates/azitserver/domain/follow/controller/FollowController.java
- azit-back/src/main/java/com/codestates/azitserver/domain/follow/dto/FollowDto.java
- azit-back/src/main/java/com/codestates/azitserver/domain/follow/entity/Follow.java
- azit-back/src/main/java/com/codestates/azitserver/domain/follow/mapper/FollowMapper.java
- azit-back/src/main/java/com/codestates/azitserver/domain/follow/repository/FollowRepository.java
- azit-back/src/main/java/com/codestates/azitserver/domain/follow/service/FollowService.java
- azit-back/src/main/java/com/codestates/azitserver/global/config/SecurityConfig.java
- azit-back/src/test/java/com/codestates/azitserver/domain/follow/controller/FollowControllerTest.java
- azit-back/src/test/java/com/codestates/azitserver/domain/follow/descrpitor/FollowFieldDescriptor.java
- azit-back/src/test/java/com/codestates/azitserver/domain/follow/helper/FollowControllerTestHelper.java
- azit-back/src/test/java/com/codestates/azitserver/domain/member/controller/descriptor/MemberFieldDescriptor.java
- azit-back/src/test/java/com/codestates/azitserver/domain/review/controller/ReviewControllerTest.java
- azit-back/src/test/java/com/codestates/azitserver/domain/stub/FollowStubData.java
- azit-back/src/test/java/com/codestates/azitserver/domain/stub/MemberStubData.java
- azit-back/src/test/java/com/codestates/azitserver/global/utils/ControllerTestHelper.java
금일 구현한 팔로우 도메인 슬라이스 테스트 및 api 문서 작성 하였습니다.
- 팔로우 테스트 코드 작성
- 팔로우 api 문서화
- 나를 팔로우한 사용자 조회시 맞팔 여부를 확인하게하는 서비스 로직 추가
> [Follow/test] 팔로우 도메인 테스트 코드 작성

- azit-front/src/components/AzitCreate/ImageModal.js
> fix: 아지트 배너 이미지 크롭 모달 수정

- azit-back/src/docs/asciidoc/index.adoc
- azit-back/src/main/java/com/codestates/azitserver/domain/auth/controller/AuthController.java
- azit-back/src/main/java/com/codestates/azitserver/domain/auth/dto/AuthDto.java
- azit-back/src/main/java/com/codestates/azitserver/domain/auth/handler/OAuthSuccessHandler.java
- azit-back/src/main/java/com/codestates/azitserver/domain/auth/service/AuthService.java
- azit-back/src/main/java/com/codestates/azitserver/global/config/SecurityConfig.java
- azit-back/src/test/java/com/codestates/azitserver/domain/auth/authControllerTest.java
토큰재발급 POST 형식으로 재변경
POST CORS 설정, POST에 바디값으로 이메일 받도록 수정, 테스트, API 문서 수정
성 공 기 원
> [auth/hotfix] 토큰 재발급

- azit-back/src/docs/asciidoc/index.adoc
- azit-back/src/main/java/com/codestates/azitserver/domain/auth/controller/AuthController.java
- azit-back/src/main/java/com/codestates/azitserver/domain/auth/dto/AuthDto.java
- azit-back/src/main/java/com/codestates/azitserver/domain/auth/dto/response/AuthResponseDto.java
- azit-back/src/main/java/com/codestates/azitserver/domain/auth/handler/OAuthSuccessHandler.java
- azit-back/src/main/java/com/codestates/azitserver/domain/auth/service/AuthService.java
- azit-back/src/main/java/com/codestates/azitserver/global/config/SecurityConfig.java
- azit-back/src/test/java/com/codestates/azitserver/domain/auth/authControllerTest.java
oauth 테스트에서 로그인 확인되어 기존 코드로 수정
oauth 응답값으로 랜덤 비번 생성 (회원 추가정보 페이지로 이동 후 회원가입 진행. 회원가입 요청 시 비밀번호 요구사항 통과 위함)
토큰재발급 방식 변경
> [auth/oauth] oauth, reIssue 코드 수정

- azit-front/src/pages/Login.js
- azit-front/src/pages/OauthGoogle.js
- azit-front/src/pages/UserPageSetting.js
- azit-front/src/util/axios.js
- azit-front/src/util/useAxios.js
- 구글 소셜 로그인 후 로그인 상태 변경 유지 기능 구현
- 토큰 재발급 기능 부분 구현
> [feat] 구글 소셜 로그인 및 토큰 재발급 기능 부분 구현

- azit-front/src/pages/AzitDetail.js
> fix: 아지트 상세페이지 호스트 이미지 div로 수정

- azit-back/src/main/resources/application.yml
프런트에서 토큰 재발급 무한요청 처리를 위해 만료시간 변경 요청하셔서 변경합니다.
application.yml 수정 
임시 수정
> [auth/hotfix] 토큰 만료시간 변경

- azit-front/src/pages/Signup.js
- 회원 가입 중복 검사 통신 코드를 수정하였습니다.
- 중복 검사 통신 기능 오류를 수정하였습니다.
> [fix] 회원가입 중복검사 통신 코드 수정 및 통신 기능 오류 수정 완료

- azit-front/src/components/AzitMember/MemberList.js
> fix: 아지트 멤버리스트 이미지 div로 수정

- azit-front/src/components/AzitMember/KickModal.js
- azit-front/src/components/AzitMember/MemberList.js
> fix: 아지트 강퇴 모달 추가

- azit-front/src/pages/AzitDetail.js
> fix: 아지트 상세 페이지 데이터 변화에 따른 코드 수정

- azit-front/src/util/axios.js
- axios response interceptor 예외 처리 코드를 수정하였습니다.
> [fix/reissue] 토큰 재발급 응답 예외 처리 수정

- azit-back/src/main/resources/application.yml
> fix : 토큰 재발급 시간 변경

- azit-back/src/main/resources/application.yml
> 토큰 재발급 시간 복구, 파일 사이즈 변경

- azit-back/src/main/resources/application.yml
> request-size 변경

- azit-back/src/main/resources/application.yml
> size복구 후 통합배포
